package com.jusika.backend.brokersafety;

/** 실제 주문 변경의 가장 우선적인 차단 사유 또는 모든 검사 통과 상태입니다. */
public enum BrokerSafetyBlockReason {
	MOCK_MODE,
	LIVE_FEATURE_DISABLED,
	KILL_SWITCH_ACTIVE,
	LIVE_ADAPTER_NOT_CONNECTED,
	LIVE_ACCOUNT_ALLOWLIST_EMPTY,
	LIVE_INSTRUMENT_ALLOWLIST_EMPTY,
	LIVE_ORDER_LIMITS_NOT_CONFIGURED,
	LIVE_DAILY_ORDER_LIMITS_NOT_CONFIGURED,
	NONE
}
