CREATE TABLE broker_mutation_audit_events (
    audit_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id VARCHAR(36),
    capability VARCHAR(64) NOT NULL,
    stage VARCHAR(32) NOT NULL,
    outcome VARCHAR(32) NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT chk_broker_mutation_audit_stage
        CHECK (stage IN ('SAFETY_GATE', 'BROKER_REQUEST')),
    CONSTRAINT chk_broker_mutation_audit_outcome
        CHECK (outcome IN ('ALLOWED', 'BLOCKED', 'STARTED', 'SUCCEEDED', 'REJECTED', 'UNKNOWN'))
);

CREATE INDEX idx_broker_mutation_audit_request_id
    ON broker_mutation_audit_events (request_id);

CREATE INDEX idx_broker_mutation_audit_occurred_at
    ON broker_mutation_audit_events (occurred_at);
