CREATE TABLE broker_unknown_incident_acknowledgement_lock (
    lock_id SMALLINT PRIMARY KEY,
    CONSTRAINT chk_broker_unknown_incident_acknowledgement_lock_singleton
        CHECK (lock_id = 1)
);

INSERT INTO broker_unknown_incident_acknowledgement_lock (lock_id) VALUES (1);

CREATE TABLE broker_unknown_incident_acknowledgements (
    acknowledgement_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    acknowledged_through_audit_event_id BIGINT NOT NULL,
    acknowledged_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_broker_unknown_incident_acknowledged_through
        UNIQUE (acknowledged_through_audit_event_id),
    CONSTRAINT chk_broker_unknown_incident_audit_event_id_positive
        CHECK (acknowledged_through_audit_event_id > 0)
);
