spring:
  config:
    activate:
      on-profile: postgres
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/jusika}
    username: ${SPRING_DATASOURCE_USERNAME:jusika}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: org.postgresql.Driver

jusika:
  broker:
    mode: ${JUSIKA_BROKER_MODE:mock}
